[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bluefin = "BbeCFPpsNTi5sqBNWjeXPtAitzqnDhYEMVxkLQodNH3B"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
